apiVersion: v1
kind: Secret
metadata:
  name: dolt-root-password
  labels:
    jenkins.io/credentials-type: "secretText"
  annotations:
    kubernetes.io/credentials-description: "Dolt root password for minordomo beads server"
stringData:
  text: {{ .Values.doltRootPassword | quote }}
