nameOverride: ""
fullnameOverride: ""

image:
  repository: dolthub/dolt-sql-server
  tag: "2.0.3"
  pullPolicy: IfNotPresent

storage:
  size: 1Gi
  storageClassName: ""

resources:
  limits:
    cpu: 400m
  requests:
    memory: 32Mi
    cpu: 10m

service:
  port: 3306
