apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dolt-server.fullname" . }}-init
  labels:
    {{- include "dolt-server.labels" . | nindent 4 }}
data:
  create-minordomo-user.sh: |
    #!/bin/sh
    dolt sql <<EOF
    CREATE USER IF NOT EXISTS 'minordomo'@'%' IDENTIFIED BY '${DOLT_MINORDOMO_PASSWORD}';
    GRANT ALL PRIVILEGES ON *.* TO 'minordomo'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
    EOF
