apiVersion: v1
kind: Service
metadata:
  name: {{ include "dolt-server.fullname" . }}
  labels:
    {{- include "dolt-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "dolt-server.selectorLabels" . | nindent 4 }}
