apiVersion: v1
kind: Service
metadata:
  name: {{ include "dolt-server.fullname" . }}
  labels:
    {{- include "dolt-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "dolt-server.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
