apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dolt-server.fullname" . }}
  labels:
    {{- include "dolt-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dolt-server.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "dolt-server.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "dolt-server.labels" . | nindent 8 }}
    spec:
      containers:
        - name: dolt-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: DOLT_ROOT_PASSWORD
              value: {{ .Values.rootPassword | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/dolt
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.storage.storageClassName }}
        storageClassName: {{ .Values.storage.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
